# Generated by Django 4.0.3 on 2022-03-22 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='personal_code'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='referral_code'),
        ),
    ]
