# Generated by Django 4.0.3 on 2022-03-21 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_alter_hammer_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hammer_user',
            name='phone',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(89000000000), django.core.validators.MaxValueValidator(89999999999)], verbose_name='phone'),
        ),
    ]
