# Generated by Django 4.0.3 on 2022-03-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_user_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hammer_User',
        ),
    ]
